from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd
import streamlit as st


ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "data" / "finpulse.duckdb"
PROCESSED_DIR = ROOT / "data" / "processed"


st.set_page_config(
    page_title="FinPulse | Financial Analytics",
    page_icon=":material/monitoring:",
    layout="wide",
    initial_sidebar_state="expanded",
)


@st.cache_data(show_spinner=False)
def load_metrics() -> pd.DataFrame:
    with duckdb.connect(str(DB_PATH), read_only=True) as connection:
        frame = connection.execute("SELECT * FROM financial_metrics ORDER BY company, period_end").df()
    frame["period_end"] = pd.to_datetime(frame["period_end"])
    return frame


@st.cache_data(show_spinner=False)
def load_growth() -> pd.DataFrame:
    with duckdb.connect(str(DB_PATH), read_only=True) as connection:
        frame = connection.execute("SELECT * FROM financial_growth ORDER BY company, period_end").df()
    frame["period_end"] = pd.to_datetime(frame["period_end"])
    return frame


@st.cache_data(show_spinner=False)
def load_csv(filename: str, parse_dates: tuple[str, ...] = ()) -> pd.DataFrame:
    path = PROCESSED_DIR / filename
    if not path.exists():
        return pd.DataFrame()
    frame = pd.read_csv(path)
    for column in parse_dates:
        if column in frame:
            frame[column] = pd.to_datetime(frame[column])
    return frame


def active_company() -> str:
    return st.session_state.company_filter


def filter_history(frame: pd.DataFrame, date_col: str) -> pd.DataFrame:
    if frame.empty or date_col not in frame:
        return frame
    if st.session_state.history_filter == "Last 5 years":
        latest = frame[date_col].max()
        frame = frame.loc[frame[date_col] >= latest - pd.DateOffset(years=5)]
    return frame


def format_billions(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "Unavailable"
    return f"-${abs(value) / 1e9:,.1f}B" if value < 0 else f"${value / 1e9:,.1f}B"


def latest_value(frame: pd.DataFrame, column: str) -> float | None:
    if frame.empty or column not in frame:
        return None
    values = frame[column].dropna()
    return None if values.empty else float(values.iloc[-1])


def executive_overview() -> None:
    company = active_company()
    metrics = load_metrics()
    growth = load_growth()
    company_metrics = filter_history(metrics.loc[metrics.company == company].copy(), "period_end")
    company_growth = filter_history(growth.loc[growth.company == company].copy(), "period_end")
    revenue_rows = company_metrics.dropna(subset=["revenue"])
    latest = revenue_rows.iloc[-1] if not revenue_rows.empty else None
    latest_growth = latest_value(company_growth, "revenue_yoy_growth")

    st.title("📊 Executive Overview")
    
    with st.expander("ℹ️ About this analysis"):
        st.markdown("""
        **Task:** Provide a high-level summary of the company's financial health, tracking revenue trends, growth, and margins.
        **Specific Work:** Extracts the latest reported XBRL facts from SEC filings, computes YoY growth and margins, and highlights any open review flags generated by the anomaly detection pipeline.
        """)

    if latest is not None:
        growth_text = "YoY growth unavailable" if latest_growth is None else f"latest available YoY growth {latest_growth:.1%}"
        gross_text = "gross margin unavailable" if pd.isna(latest.gross_margin) else f"gross margin {latest.gross_margin:.1%}"
        operating_text = "operating margin unavailable" if pd.isna(latest.operating_margin) else f"operating margin {latest.operating_margin:.1%}"
        st.caption(
            f"{company} | Quarter ended {latest.period_end:%d %b %Y}: "
            f"revenue {format_billions(latest.revenue)}, {growth_text}, "
            f"{gross_text}, {operating_text}."
        )
    else:
        st.caption(f"{company} | No reported revenue in the selected history.")
    
    st.divider()
    kpis = st.columns(4)
    kpis[0].metric("Quarterly revenue", format_billions(None if latest is None else latest.revenue))
    kpis[1].metric("YoY revenue growth", "Unavailable" if latest_growth is None else f"{latest_growth:.1%}")
    kpis[2].metric("Gross margin", "Unavailable" if latest is None or pd.isna(latest.gross_margin) else f"{latest.gross_margin:.1%}")
    kpis[3].metric("Operating margin", "Unavailable" if latest is None or pd.isna(latest.operating_margin) else f"{latest.operating_margin:.1%}")
    st.divider()

    left, right = st.columns([1.55, 1])
    with left:
        st.subheader("📈 Revenue trend")
        if revenue_rows.empty:
            st.info("No reported revenue in the selected period.")
        else:
            chart = revenue_rows[["period_end", "revenue"]].set_index("period_end") / 1e9
            chart = chart.rename(columns={"revenue": "Revenue ($B)"})
            st.line_chart(chart, height=330, color=["#176B87"])
    with right:
        st.subheader("🚀 Growth and margins")
        chart = company_growth.set_index("period_end")[["revenue_yoy_growth"]].rename(columns={"revenue_yoy_growth": "YoY revenue growth"})
        chart = chart.join(company_metrics.set_index("period_end")[["gross_margin", "operating_margin"]], how="outer")
        chart = chart.rename(columns={"gross_margin": "Gross margin", "operating_margin": "Operating margin"})
        st.line_chart(chart, height=330, color=["#176B87", "#4C956C", "#D97941"])

    residuals = load_csv("forecast_residual_anomalies.csv", ("target_period_end",))
    residuals = residuals.loc[residuals.company == company] if not residuals.empty else residuals
    margin_flags = load_csv("margin_anomalies.csv", ("period_end",))
    margin_flags = margin_flags.loc[margin_flags.company == company] if not margin_flags.empty else margin_flags
    st.subheader("🚨 Open review flags")
    flags = st.columns(2)
    flags[0].metric("Forecast residual flags", len(residuals))
    flags[1].metric("Margin candidates", len(margin_flags))
    
    st.download_button(
        "📥 Download Company Metrics",
        data=company_metrics.to_csv(index=False).encode("utf-8"),
        file_name=f"{company.lower()}_metrics.csv",
        mime="text/csv",
    )
    st.caption("Historical reported values are latest-restated where the SEC facts service provides later comparative filings.")


def forecast_vs_actual() -> None:
    company = active_company()
    forecasts = load_csv("forecast_variance_by_model.csv", ("origin_period_end", "target_period_end"))
    if forecasts.empty:
        st.error("Backtest outputs are missing. Run src/backtest.py and src/variance.py first.")
        return
    model_names = sorted(forecasts.model.unique())
    chosen_model = st.selectbox("Model", model_names, index=model_names.index("naive") if "naive" in model_names else 0)
    frame = forecasts.loc[(forecasts.company == company) & (forecasts.model == chosen_model)].copy()
    frame = filter_history(frame, "target_period_end").sort_values("target_period_end")

    st.title("🎯 Forecast vs Actual")
    
    with st.expander("ℹ️ About this analysis"):
        st.markdown("""
        **Task:** Evaluate the performance of different forecasting models against actual historical revenue.
        **Specific Work:** Uses an expanding-window rolling-origin backtest to generate one-quarter-ahead forecasts for each model. Calculates error metrics like MAE, RMSE, and MAPE to identify the most accurate model.
        """)

    if frame.empty:
        st.info("No eligible rolling-origin forecasts for this company and model.")
        return
        
    mae = frame.absolute_error.mean()
    rmse = (frame.squared_error.mean()) ** 0.5
    mape = frame.ape.mean()
    smape = frame.smape.mean()
    
    st.caption(
        f"{company} | {chosen_model} achieved {mape:.1%} MAPE and {format_billions(mae)} MAE "
        f"across {len(frame)} rolling one-quarter-ahead origins."
    )
    
    st.divider()
    kpis = st.columns(4)
    kpis[0].metric("Forecast origins", len(frame))
    kpis[1].metric("MAE", format_billions(mae))
    kpis[2].metric("RMSE", format_billions(rmse))
    kpis[3].metric("MAPE / sMAPE", f"{mape:.1%} / {smape:.1%}")
    st.divider()

    st.subheader("📉 Historical Backtest Chart")
    chart = frame[["target_period_end", "actual", "forecast"]].set_index("target_period_end") / 1e9
    chart = chart.rename(columns={"actual": "Actual ($B)", "forecast": "Forecast ($B)"})
    st.line_chart(chart, height=360, color=["#176B87", "#D97941"])
    
    st.subheader("📋 Forecast Variance Data")
    table = frame[["target_period_end", "actual", "forecast", "variance_amount", "variance_pct_of_forecast"]].copy()
    table["actual"] = table.actual.map(format_billions)
    table["forecast"] = table.forecast.map(format_billions)
    table["variance_amount"] = table.variance_amount.map(lambda value: format_billions(value))
    table["variance_pct_of_forecast"] = table.variance_pct_of_forecast.map(lambda value: f"{value:.1%}")
    table = table.rename(columns={
        "target_period_end": "Target period",
        "actual": "Actual revenue",
        "forecast": "Forecast revenue",
        "variance_amount": "Actual - forecast",
        "variance_pct_of_forecast": "Variance %",
    })
    st.dataframe(table, hide_index=True, use_container_width=True)
    
    st.download_button(
        "📥 Download Forecast Data",
        data=frame.to_csv(index=False).encode("utf-8"),
        file_name=f"{company.lower()}_forecasts_{chosen_model}.csv",
        mime="text/csv",
    )
    
    st.caption("This is the historical backtest view. The project does not yet produce a validated four-quarter forward forecast or prediction intervals.")



def variance_and_anomalies() -> None:
    company = active_company()
    residuals = load_csv("naive_residual_scores.csv", ("target_period_end",))
    margin_scores = load_csv("margin_anomaly_scores.csv", ("period_end",))
    margin_eligibility = load_csv("margin_anomaly_eligibility.csv")
    if residuals.empty or margin_scores.empty:
        st.error("Phase 6 outputs are missing. Run src/variance.py first.")
        return
    residuals = residuals.loc[residuals.company == company].copy()
    residuals = filter_history(residuals, "target_period_end")
    margin_scores = margin_scores.loc[margin_scores.company == company].copy()
    margin_scores = filter_history(margin_scores, "period_end")
    eligibility = margin_eligibility.loc[margin_eligibility.company == company]

    flagged_residuals = residuals.loc[residuals.anomaly_flag]
    flagged_margins = margin_scores.loc[margin_scores.anomaly_flag]

    st.title("⚠️ Variance and Anomalies")
    
    with st.expander("ℹ️ About this analysis"):
        st.markdown("""
        **Task:** Identify unusual financial results that warrant deeper manual review.
        **Specific Work:** Applies statistical tests (z-scores on naive residuals) and machine learning (Isolation Forest) to detect anomalies in revenue forecasts and profit margins across historical quarters.
        """)

    st.caption(
        f"{company} history contains {len(flagged_residuals)} forecast residual flags and "
        f"{len(flagged_margins)} margin candidates for filing-level review."
    )
    
    st.divider()
    kpis = st.columns(3)
    kpis[0].metric("Residual flags", len(flagged_residuals))
    kpis[1].metric("Margin candidates", len(flagged_margins))
    kpis[2].metric("Margin series eligible", int(eligibility.status.eq("scored retrospectively").sum()))
    st.divider()

    st.subheader("📉 Actual vs Naive Forecast Variance")
    frame = residuals.sort_values("target_period_end").set_index("target_period_end")
    chart = frame[["variance_pct_of_forecast"]].mul(100).rename(columns={"variance_pct_of_forecast": "Variance % of forecast"})
    st.line_chart(chart, height=290, color=["#176B87"])
    
    if flagged_residuals.empty:
        st.info("No residual exceeded the review threshold in the selected period.")
    else:
        display = flagged_residuals[["target_period_end", "variance_amount", "variance_pct_of_forecast", "trailing_residual_zscore"]].copy()
        display["variance_amount"] = display.variance_amount.map(format_billions)
        display["variance_pct_of_forecast"] = display.variance_pct_of_forecast.map(lambda value: f"{value:.1%}")
        st.dataframe(display.rename(columns={
            "target_period_end": "Target period",
            "variance_amount": "Actual - forecast",
            "variance_pct_of_forecast": "Variance %",
            "trailing_residual_zscore": "Trailing z-score",
        }), hide_index=True, use_container_width=True)
        
        st.download_button(
            "📥 Download Residual Flags",
            data=flagged_residuals.to_csv(index=False).encode("utf-8"),
            file_name=f"{company.lower()}_residual_flags.csv",
            mime="text/csv",
        )

    st.subheader("🔍 Margin Candidates")
    if flagged_margins.empty:
        st.info("No margin candidates in the selected period.")
    else:
        display = flagged_margins[["period_end", "metric", "margin_value", "anomaly_score"]].sort_values("period_end", ascending=False)
        display["margin_value"] = display.margin_value.map(lambda value: f"{value:.1%}")
        display["anomaly_score"] = display.anomaly_score.map(lambda value: f"{value:.3f}")
        st.dataframe(display.rename(columns={
            "period_end": "Period",
            "metric": "Metric",
            "margin_value": "Margin",
            "anomaly_score": "Isolation Forest score",
        }), hide_index=True, use_container_width=True)
        
        st.download_button(
            "📥 Download Margin Candidates",
            data=flagged_margins.to_csv(index=False).encode("utf-8"),
            file_name=f"{company.lower()}_margin_candidates.csv",
            mime="text/csv",
        )
        
    st.caption("Statistical flags need filing-level and business-event review before being treated as explanations.")


def model_comparison() -> None:
    company = active_company()
    metrics = load_csv("backtest_metrics.csv")
    if metrics.empty:
        st.error("Backtest metrics are missing. Run src/backtest.py first.")
        return
    frame = metrics.loc[metrics.company == company].sort_values("mae").copy()
    
    st.title("🏆 Model Comparison")
    
    with st.expander("ℹ️ About this analysis"):
        st.markdown("""
        **Task:** Compare all evaluated forecasting models to select the most reliable method for future revenue projections.
        **Specific Work:** Aggregates error metrics across all models and ranks them by Mean Absolute Error (MAE). Also reports Mean Absolute Scaled Error (MASE) to evaluate model skill relative to a random walk baseline.
        """)

    st.caption(f"{company}  |  Expanding-window rolling-origin results")
    if frame.empty:
        st.info("No eligible model comparison for this company.")
        return
        
    winner = frame.iloc[0]
    st.caption(
        f"{company}'s lowest observed MAE is {format_billions(winner.mae)} with {winner.model} "
        f"across {int(winner.forecast_origins)} origins; the same small backtest was used to select and score it."
    )
    
    st.divider()
    st.metric("Lowest backtest MAE", winner.model, f"{winner.mae_skill_vs_naive:.1%} MAE skill vs naive")
    st.divider()
    
    st.subheader("📊 Relative Performance (MASE)")
    chart = frame.set_index("model")[["mase"]].sort_values("mase")
    st.bar_chart(chart, height=320, horizontal=True, color="#176B87")

    st.subheader("📋 Model Metrics")
    display = frame[["model", "forecast_origins", "mae", "rmse", "mape", "smape", "mase", "mae_skill_vs_naive"]].copy()
    display["mae"] = display.mae.map(format_billions)
    display["rmse"] = display.rmse.map(format_billions)
    for column in ["mape", "smape", "mae_skill_vs_naive"]:
        display[column] = display[column].map(lambda value: f"{value:.1%}")
    display["mase"] = display.mase.map(lambda value: f"{value:.3f}")
    display = display.rename(columns={
        "model": "Model",
        "forecast_origins": "Origins",
        "mae": "MAE ($)",
        "rmse": "RMSE ($)",
        "mape": "MAPE",
        "smape": "sMAPE",
        "mase": "MASE",
        "mae_skill_vs_naive": "MAE skill vs naive",
    })
    st.dataframe(display, hide_index=True, use_container_width=True)
    
    st.download_button(
        "📥 Download Company Comparison",
        data=frame.to_csv(index=False).encode("utf-8"),
        file_name=f"{company.lower()}_model_comparison.csv",
        mime="text/csv",
    )
    st.caption("The best row is in-sample backtest-selected and may be optimistic. Keep the naive baseline visible during model review.")


def main() -> None:
    if not DB_PATH.exists():
        st.error("FinPulse DuckDB is missing. Run the extraction, transform, and load steps first.")
        st.stop()
    companies = sorted(load_metrics().company.unique())
    
    st.sidebar.title("📈 FinPulse Analytics")
    st.sidebar.markdown("---")
    
    st.sidebar.selectbox("Company", companies, key="company_filter")
    st.sidebar.selectbox("History", ["Full history", "Last 5 years"], key="history_filter")
    
    st.sidebar.markdown("---")
    st.sidebar.caption("High-end Dashboard for Financial Forecasting and Variance Analysis.")
    
    pages = [
        st.Page(executive_overview, title="Executive Overview", icon=":material/space_dashboard:"),
        st.Page(forecast_vs_actual, title="Forecast vs Actual", icon=":material/query_stats:"),
        st.Page(variance_and_anomalies, title="Variance and Anomalies", icon=":material/warning:"),
        st.Page(model_comparison, title="Model Comparison", icon=":material/leaderboard:"),
    ]
    st.navigation(pages).run()


if __name__ == "__main__":
    main()
